version: "2"

services:
  mysql80:
    image: mysql:8.0
    container_name: mysql80
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "notes001"
      MYSQL_PASSWORD: "secret"
      MYSQL_DATABASE: "edx_notes_api"
  es:
    image: elasticsearch:7.8.0
    container_name: es
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.port=9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  notes:
    # Uncomment this line to use the official course-discovery base image
    image: openedx/edx-notes-api:latest

    # Uncomment the next two lines to build from a local configuration repo
    # build: ../configuration/docker/build/discovery/

    container_name: edx_notes_api
    volumes:
      - ..:/edx/app/edx_notes_api/edx_notes_api
    command: tail -f /dev/null
    depends_on:
      - "mysql80"
      - "es"
    environment:
      CONN_MAX_AGE: 60
      DB_ENGINE: "django.db.backends.mysql"
      DB_HOST: "db"
      DB_NAME: "edx_notes_api"
      DB_PASSWORD: ""
      DB_PORT: "3306"
      DB_USER: "root"
      ENABLE_DJANGO_TOOLBAR: 1
      ELASTICSEARCH_URL: "http://es:9200"

volumes:
  elasticsearch_data:
    driver: local
