# Override values.yaml that are suitable for a development environment on a laptop.

# May include things like default passwords and resource limits and should not be launched in a production environment.

app:
  # config is exposed to the app container on disk as a secret
  # these values are exposed to the app via django_settings
  config: 
    CLIENT_ID: some_client_id
    CLIENT_SECRET: some_secret
    DATABASES:
      default:
        PASSWORD: 'testingthething'
    SECRET_KEY: zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
    resources: 
      requests:
        cpu: 25m
        memory: 512Mi 
      limits:
        cpu: 100m
        memory: 512Mi
elasticsearch:
  enabled: true
  # Permit co-located instances for solitary minikube virtual machines.
  antiAffinity: "soft"

  # Shrink default JVM heap.
  esJavaOpts: "-Xmx128m -Xms128m"

  # Allocate smaller chunks of memory per pod.
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "250m"
      memory: "512M"

  # Request smaller persistent volumes.
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "standard"
    resources:
      requests:
        storage: 100M

mysql:
  enabled: true

migrations:
  enabled: true
